/**
 * Snapshots the resolved dependency tree and the audit posture, and fails when a migration makes
 * the runtime posture worse.
 *
 * A version walk replaces most of the tree, so a PR arrives as a five-figure lockfile diff that no
 * reviewer reads. This turns it into two reviewable artifacts and one gate.
 *
 * The distinction that matters is **runtime vs build-time**. Most advisories in an Angular
 * workspace are in build tooling that never reaches a browser; treating those as equivalent to a
 * vulnerability in `@angular/core` trains people to ignore the number. Only the production
 * dependency closure is gated.
 *
 *   node tools/dependency-report.mjs --write   regenerate deps-report/
 *   node tools/dependency-report.mjs --check   fail on a new runtime advisory; print the tree diff
 */
import { readFileSync, writeFileSync, existsSync, mkdirSync } from 'node:fs';
import { execFileSync } from 'node:child_process';
import { resolve } from 'node:path';

const DIR = resolve('deps-report');
const TREE = resolve(DIR, 'tree.txt');
const AUDIT = resolve(DIR, 'audit.md');

const SEVERITY = ['critical', 'high', 'moderate', 'low', 'info'];

function audit(productionOnly) {
  const args = ['audit', '--json', ...(productionOnly ? ['--omit=dev'] : [])];
  let raw;
  try {
    raw = execFileSync('npm', args, { encoding: 'utf8', maxBuffer: 64 * 1024 * 1024 });
  } catch (error) {
    // npm audit exits non-zero whenever it finds anything; the JSON is still on stdout.
    raw = error.stdout;
  }
  if (!raw) throw new Error(`npm ${args.join(' ')} produced no output`);

  const parsed = JSON.parse(raw);
  const advisories = new Map();
  for (const info of Object.values(parsed.vulnerabilities ?? {})) {
    for (const via of info.via) {
      if (typeof via === 'object' && via.title) {
        advisories.set(`${via.name}: ${via.title}`, { package: via.name, severity: via.severity, title: via.title });
      }
    }
  }
  return { totals: parsed.metadata.vulnerabilities, advisories };
}

function tree() {
  const lock = JSON.parse(readFileSync('package-lock.json', 'utf8'));
  const entries = [];
  for (const [path, meta] of Object.entries(lock.packages)) {
    if (!path || !meta.version) continue;
    entries.push(`${path.replace(/^node_modules\//, '').replace(/node_modules\//g, '> ')}@${meta.version}`);
  }
  return [...new Set(entries)].sort().join('\n') + '\n';
}

function renderAudit(runtime, all) {
  const buildOnly = [...all.advisories.values()].filter((a) => !runtime.advisories.has(`${a.package}: ${a.title}`));
  const bySeverity = (a, b) => SEVERITY.indexOf(a.severity) - SEVERITY.indexOf(b.severity) || a.package.localeCompare(b.package);

  const lines = [
    '# Dependency audit — `digital_banking_mock`',
    '',
    'Generated by `tools/dependency-report.mjs`. Do not edit by hand.',
    '',
    '**Runtime** advisories are in the production dependency closure and ship to a browser.',
    '**Build-time** advisories are in tooling that does not. Only the runtime list is gated —',
    'counting them together is how a real finding gets lost in tooling noise.',
    '',
    `## Runtime — ${runtime.totals.total} advisory instance(s)`,
    '',
  ];

  const runtimeList = [...runtime.advisories.values()].sort(bySeverity);
  if (runtimeList.length) {
    lines.push('| Severity | Package | Advisory |', '|---|---|---|');
    for (const a of runtimeList) lines.push(`| ${a.severity} | \`${a.package}\` | ${a.title} |`);
  } else {
    lines.push('_None._');
  }

  lines.push('', `## Build-time only — ${buildOnly.length} distinct advisory/advisories`, '');
  if (buildOnly.length) {
    lines.push('| Severity | Package |', '|---|---|');
    const counted = new Map();
    for (const a of buildOnly.sort(bySeverity)) counted.set(a.package, (counted.get(a.package) ?? 0) + 1);
    for (const [pkg, count] of counted) lines.push(`| — | \`${pkg}\` × ${count} |`);
  } else {
    lines.push('_None._');
  }

  lines.push('', '## Totals reported by npm', '', '```', `all:     ${JSON.stringify(all.totals)}`, `runtime: ${JSON.stringify(runtime.totals)}`, '```', '');
  return lines.join('\n');
}

function diffLines(before, after) {
  const b = new Set(before.trim().split('\n'));
  const a = new Set(after.trim().split('\n'));
  const name = (line) => line.slice(0, line.lastIndexOf('@'));
  const beforeByName = new Map([...b].map((l) => [name(l), l]));
  const afterByName = new Map([...a].map((l) => [name(l), l]));

  const added = [...afterByName.keys()].filter((n) => !beforeByName.has(n));
  const removed = [...beforeByName.keys()].filter((n) => !afterByName.has(n));
  const changed = [...afterByName.keys()].filter((n) => beforeByName.has(n) && beforeByName.get(n) !== afterByName.get(n));
  return { added, removed, changed };
}

mkdirSync(DIR, { recursive: true });

const currentTree = tree();
const runtime = audit(true);
const all = audit(false);
const currentAudit = renderAudit(runtime, all);

if (!process.argv.includes('--check')) {
  writeFileSync(TREE, currentTree);
  writeFileSync(AUDIT, currentAudit);
  console.log(`Wrote ${TREE} and ${AUDIT}`);
  console.log(`Runtime advisories: ${runtime.advisories.size}. Build-time: ${all.advisories.size - runtime.advisories.size}.`);
  process.exit(0);
}

if (!existsSync(TREE) || !existsSync(AUDIT)) {
  console.error(`No committed report in ${DIR}. Run: node tools/dependency-report.mjs --write`);
  process.exit(1);
}

const { added, removed, changed } = diffLines(readFileSync(TREE, 'utf8'), currentTree);
console.log('### Dependency change\n');
console.log(`| Added | Removed | Version-changed |`);
console.log(`|---|---|---|`);
console.log(`| ${added.length} | ${removed.length} | ${changed.length} |\n`);
if (added.length) console.log(`Added: ${added.slice(0, 40).join(', ')}${added.length > 40 ? `, and ${added.length - 40} more` : ''}\n`);

const baselineRuntime = new Set(
  readFileSync(AUDIT, 'utf8')
    .split('\n')
    .filter((l) => l.startsWith('| ') && l.includes('` |'))
    .map((l) => l.split('|')[2].trim().replace(/`/g, '') + ': ' + l.split('|')[3].trim())
);

const newRuntime = [...runtime.advisories.keys()].filter((key) => !baselineRuntime.has(key));

console.log(`Runtime advisories: ${runtime.advisories.size} (baseline ${baselineRuntime.size}).\n`);

if (newRuntime.length) {
  console.error(`FAIL — ${newRuntime.length} new runtime advisory/advisories:\n`);
  for (const key of newRuntime) console.error(`  - ${key}`);
  console.error('\nA migration may not make the shipped dependency posture worse. Regenerate with');
  console.error('--write only once the advisory is understood and accepted on the PR.');
  process.exit(1);
}

console.log('PASS — no new runtime advisory. Regenerate the report with --write when versions move.');
